apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ia-case-access-api
spec:
  values:
    java:
      ingressHost: ia-case-access-api-aat.service.core-compute-aat.internal
      environment:
        IDAM_URL: "https://idam-web-public.aat.platform.hmcts.net"
        S2S_URL: "http://rpe-service-auth-provider-aat.service.core-compute-aat.internal"
